POST {{host}}/firebase/sync
Content-Type: application/json
Authorization: Bearer hGOjZJOwdQ572rC1q6RhYs6kinzGYGtjAGsPX2MWqQc=

{}

###

POST https://007d-185-208-231-151.ngrok-free.app/firebase/sync
Content-Type: application/json
Authorization: Bearer hGOjZJOwdQ572rC1q6RhYs6kinzGYGtjAGsPX2MWqQc=

{}

###

POST {{host}}/auth/sync
Content-Type: application/json
Authorization: Bearer xxx111222333

###

GET {{host}}/auth/test
Content-Type: application/json
Authorization: Bearer xxx111222333

###

GET {{host}}/system-modules/seed
Content-Type: application/json

###

POST {{host}}/roles
Content-Type: application/json

{
  "name": "admin",
  "description": "Admin role"
}

###

POST {{host}}/roles/1/permissions
Content-Type: application/json

{
  "permissionNames": [
    "UserManagement:viewUsers"
  ]
}

###

GET {{host}}/roles/1
